/**
 * Central route data layer.
 *
 * Single source of truth for the 30 indexed intercity routes from Prague.
 * Consumed by:
 *   - app/routes/page.tsx (hub listing)
 *   - app/sitemap.ts (sitemap entries)
 *
 * Per-route page.tsx files still own their own body content (hero copy,
 * inclusions, FAQs, day-trip configs, JSON-LD schema). Move those to this
 * file only if a stronger refactor is explicitly planned.
 *
 * Generated from existing page data by tools/phase4_build_routes_lib.py.
 * Manual edits are safe — the script is a one-shot bootstrap, not a sync.
 */

export type RouteTier = 'green' | 'yellow'

export type RoutePrices = {
  eClass: number
  sClass: number
  vClass: number
}

export type Route = {
  slug: string                // 'prague-vienna' (URL path after /routes/)
  from: string                // 'Prague'
  city: string                // 'Vienna' (destination display name)
  h2: string                  // hub card H2, e.g. 'Prague to Vienna Private Chauffeur'
  country: string             // 'Austria'
  tier: RouteTier             // 'green' | 'yellow'
  distanceKm: number          // 330
  distance: string            // '~330 km' (display string)
  duration: string            // '~3.5 hours'
  road: string | null         // 'Motorway D1/A22' or null
  prices: RoutePrices         // { eClass: 485, sClass: 725, vClass: 560 }
  priceFrom: string           // 'From €485' (display string for hub)
  description: string         // hub card description
  notes: string[]             // hub card bullet notes
  image?: string | null       // optional hero background image path
  wordTarget: 900 | 1500      // content depth target from strategy
  metadataTitle: string       // per-page <title>
}

export const ROUTES: Route[] = [
  {
    slug: 'prague-kutna-hora',
    from: 'Prague',
    city: 'Kutná Hora',
    h2: 'Prague to Kutná Hora Transfer',
    country: 'Czech Republic',
    tier: 'green',
    distanceKm: 70,
    distance: '~70 km',
    duration: '~1 hour',
    road: null,
    prices: { eClass: 115, sClass: 170, vClass: 135 },
    priceFrom: 'From €115',
    description: 'The silver-mining city of medieval Bohemia. 70 km east — UNESCO old town, the Sedlec Ossuary, and the Cathedral of St. Barbara. The most accessible day trip from Prague by private car.',
    notes: ['Sedlec Ossuary visit available on request', 'Return same day available'],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Kutná Hora Private Transfer — From €115',
  },
  {
    slug: 'prague-plzen',
    from: 'Prague',
    city: 'Plzeň',
    h2: 'Prague to Plzeň Transfer',
    country: 'Czech Republic',
    tier: 'yellow',
    distanceKm: 90,
    distance: '~90 km',
    duration: '~1 hour',
    road: 'Motorway D5',
    prices: { eClass: 150, sClass: 220, vClass: 170 },
    priceFrom: 'From €150',
    description: 'Home of Pilsner Urquell and West Bohemia\'s industrial capital. 90 km west on the D5 — brewery tours, the Republic Square, and a thriving Czech tech sector.',
    notes: ['Pilsner Urquell brewery tour available on request'],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to Plzeň Private Transfer — From €150',
  },
  {
    slug: 'prague-liberec',
    from: 'Prague',
    city: 'Liberec',
    h2: 'Prague to Liberec Chauffeur',
    country: 'Czech Republic',
    tier: 'yellow',
    distanceKm: 105,
    distance: '~105 km',
    duration: '~1.5 hours',
    road: null,
    prices: { eClass: 175, sClass: 255, vClass: 200 },
    priceFrom: 'From €175',
    description: 'North Bohemia\'s mountain capital. 105 km north — Jizera Mountains cable car, the neo-baroque town hall, and Czech glass tradition. Day trip distance from Prague.',
    notes: ['Ski resorts and hiking in the Jizera Mountains nearby'],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to Liberec Private Chauffeur — From €175',
  },
  {
    slug: 'prague-pardubice',
    from: 'Prague',
    city: 'Pardubice',
    h2: 'Prague to Pardubice Transfer',
    country: 'Czech Republic',
    tier: 'yellow',
    distanceKm: 110,
    distance: '~110 km',
    duration: '~1.5 hours',
    road: 'Motorway D11',
    prices: { eClass: 180, sClass: 270, vClass: 210 },
    priceFrom: 'From €180',
    description: 'East Bohemia\'s equestrian city. 110 km east on the D11 — the Grand Pardubice Steeplechase, a well-preserved Old Town, and close ties with Hradec Králové.',
    notes: ['Hradec Králové stop available en route'],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to Pardubice Private Transfer — From €180',
  },
  {
    slug: 'prague-hradec-kralove',
    from: 'Prague',
    city: 'Hradec Králové',
    h2: 'Prague to Hradec Králové Chauffeur',
    country: 'Czech Republic',
    tier: 'yellow',
    distanceKm: 115,
    distance: '~115 km',
    duration: '~1.5 hours',
    road: 'Motorway D11',
    prices: { eClass: 190, sClass: 280, vClass: 220 },
    priceFrom: 'From €190',
    description: 'The royal city on the upper Elbe. 115 km east — modernist architecture by Kotěra and Gočár, East Bohemia Museum, and the Czech military history capital.',
    notes: ['Pardubice stop available en route'],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to Hradec Králové Private Transfer — From €190',
  },
  {
    slug: 'prague-karlovy-vary',
    from: 'Prague',
    city: 'Karlovy Vary',
    h2: 'Prague to Karlovy Vary Transfer',
    country: 'Czech Republic',
    tier: 'green',
    distanceKm: 130,
    distance: '~130 km',
    duration: '~1.5 hours',
    road: 'Motorway D6',
    prices: { eClass: 215, sClass: 320, vClass: 250 },
    priceFrom: 'From €215',
    description: 'The crown jewel of the Bohemian spa triangle. 130 km west on the D6 — film festival, thermal colonnades, Becherovka, and the most celebrated spa destination in Central Europe.',
    notes: ['Mariánské Lázně and Františkovy Lázně nearby'],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Karlovy Vary Private Transfer — From €215',
  },
  {
    slug: 'prague-dresden',
    from: 'Prague',
    city: 'Dresden',
    h2: 'Prague to Dresden Private Transfer',
    country: 'Germany',
    tier: 'green',
    distanceKm: 150,
    distance: '~150 km',
    duration: '~1.5 hours',
    road: 'Motorway D8/A17',
    prices: { eClass: 250, sClass: 370, vClass: 285 },
    priceFrom: 'From €250',
    description: 'Just 150 km through the Saxon Switzerland national park. The closest major German city to Prague — Semperoper, Zwinger, and Frauenkirche.',
    notes: [],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Dresden Private Transfer | Door-to-Door in 2 Hours | Prestigo',
  },
  {
    slug: 'prague-ceske-budejovice',
    from: 'Prague',
    city: 'České Budějovice',
    h2: 'Prague to České Budějovice Transfer',
    country: 'Czech Republic',
    tier: 'yellow',
    distanceKm: 155,
    distance: '~155 km',
    duration: '~2 hours',
    road: null,
    prices: { eClass: 255, sClass: 380, vClass: 295 },
    priceFrom: 'From €255',
    description: 'South Bohemia\'s capital and home of Budvar. 155 km south — the baroque main square, Budějovický Budvar brewery, and a gateway to Šumava and Český Krumlov.',
    notes: ['Český Krumlov nearby — add as a stop on request'],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to České Budějovice Private Transfer — From €255',
  },
  {
    slug: 'prague-marianske-lazne',
    from: 'Prague',
    city: 'Mariánské Lázně',
    h2: 'Prague to Mariánské Lázně Chauffeur',
    country: 'Czech Republic',
    tier: 'yellow',
    distanceKm: 165,
    distance: '~165 km',
    duration: '~2 hours',
    road: 'Motorway D6',
    prices: { eClass: 270, sClass: 405, vClass: 315 },
    priceFrom: 'From €270',
    description: 'The green pearl of the Bohemian spa triangle. 165 km west — Chopin\'s summer retreat, colonnaded springs, and the most elegant atmosphere in Czech spa country.',
    notes: ['Karlovy Vary stop available en route', 'Františkovy Lázně nearby'],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to Mariánské Lázně Private Transfer — From €270',
  },
  {
    slug: 'prague-cesky-krumlov',
    from: 'Prague',
    city: 'Český Krumlov',
    h2: 'Prague to Český Krumlov Chauffeur',
    country: 'Czech Republic',
    tier: 'green',
    distanceKm: 175,
    distance: '~175 km',
    duration: '~2.5 hours',
    road: null,
    prices: { eClass: 290, sClass: 430, vClass: 335 },
    priceFrom: 'From €290',
    description: 'UNESCO old town on the Vltava bend, 175 km south. The most requested day trip from Prague — baroque castle, cobbled streets, and the river below. Private and punctual.',
    notes: ['Return same day available', 'České Budějovice stop on request'],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Český Krumlov Private Transfer — From €290',
  },
  {
    slug: 'prague-frantiskovy-lazne',
    from: 'Prague',
    city: 'Františkovy Lázně',
    h2: 'Prague to Františkovy Lázně Transfer',
    country: 'Czech Republic',
    tier: 'yellow',
    distanceKm: 175,
    distance: '~175 km',
    duration: '~2.5 hours',
    road: 'Motorway D6',
    prices: { eClass: 290, sClass: 430, vClass: 335 },
    priceFrom: 'From €290',
    description: 'The smallest and most refined of the Bohemian spa towns. 175 km west — Empire-style colonnades, pure mineral springs, and the quietest corner of West Bohemia.',
    notes: ['Mariánské Lázně and Karlovy Vary nearby'],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to Františkovy Lázně Private Transfer — From €290',
  },
  {
    slug: 'prague-linz',
    from: 'Prague',
    city: 'Linz',
    h2: 'Prague to Linz Private Transfer',
    country: 'Austria',
    tier: 'green',
    distanceKm: 195,
    distance: '~195 km',
    duration: '~2.5 hours',
    road: null,
    prices: { eClass: 320, sClass: 480, vClass: 370 },
    priceFrom: 'From €320',
    description: 'Austria\'s industrial capital and European Capital of Culture. 195 km south — Ars Electronica, the Danube, and a two-and-a-half-hour drive from Prague\'s centre.',
    notes: [],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Linz Private Transfer — From €320',
  },
  {
    slug: 'prague-brno',
    from: 'Prague',
    city: 'Brno',
    h2: 'Prague to Brno Chauffeur',
    country: 'Czech Republic',
    tier: 'green',
    distanceKm: 205,
    distance: '~205 km',
    duration: '~2.5 hours',
    road: 'Motorway D1',
    prices: { eClass: 340, sClass: 500, vClass: 390 },
    priceFrom: 'From €340',
    description: 'Moravia\'s capital and the Czech second city. 205 km southeast on the D1 — tech sector, trade fairs, Špilberk.',
    notes: [],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Brno Private Transfer — From €340',
  },
  {
    slug: 'prague-passau',
    from: 'Prague',
    city: 'Passau',
    h2: 'Prague to Passau Private Transfer',
    country: 'Germany',
    tier: 'green',
    distanceKm: 220,
    distance: '~220 km',
    duration: '~2.5 hours',
    road: null,
    prices: { eClass: 365, sClass: 540, vClass: 420 },
    priceFrom: 'From €365',
    description: 'The city of three rivers. 220 km southwest — where the Danube, Inn, and Ilz meet, beneath the baroque Dom and the Veste Oberhaus fortress.',
    notes: ['Linz stopover available on the Danube route'],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Passau Private Transfer — From €365',
  },
  {
    slug: 'prague-leipzig',
    from: 'Prague',
    city: 'Leipzig',
    h2: 'Prague to Leipzig Private Chauffeur',
    country: 'Germany',
    tier: 'green',
    distanceKm: 260,
    distance: '~165 km',
    duration: '~2 hours',
    road: 'Motorway D8/A14',
    prices: { eClass: 270, sClass: 405, vClass: 315 },
    priceFrom: 'From €270',
    description: 'Bach\'s city and Germany\'s new creative capital. 165 km north on the D8 — the most direct route into Saxony, with a Dresden stopover available.',
    notes: ['Dresden stopover available en route'],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Leipzig Private Transfer — From €270',
  },
  {
    slug: 'prague-olomouc',
    from: 'Prague',
    city: 'Olomouc',
    h2: 'Prague to Olomouc Private Transfer',
    country: 'Czech Republic',
    tier: 'yellow',
    distanceKm: 280,
    distance: '~280 km',
    duration: '~3 hours',
    road: 'Motorway D1/D46',
    prices: { eClass: 460, sClass: 685, vClass: 530 },
    priceFrom: 'From €460',
    description: 'Moravia\'s hidden capital and university city. 280 km east — six baroque fountains, the UNESCO Holy Trinity Column, and Czech café culture at its finest.',
    notes: ['Brno stop available en route'],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to Olomouc Private Transfer — From €460',
  },
  {
    slug: 'prague-regensburg',
    from: 'Prague',
    city: 'Regensburg',
    h2: 'Prague to Regensburg Private Transfer',
    country: 'Germany',
    tier: 'green',
    distanceKm: 285,
    distance: '~285 km',
    duration: '~3 hours',
    road: 'Motorway D5/A93',
    prices: { eClass: 470, sClass: 700, vClass: 540 },
    priceFrom: 'From €470',
    description: 'Bavaria\'s best-preserved medieval city. 285 km southwest — the 12th-century stone bridge, the UNESCO Altstadt, and the Danube — one hour from Munich.',
    notes: ['Nuremberg and Munich within easy reach from Regensburg'],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Regensburg Private Transfer — From €470',
  },
  {
    slug: 'prague-wroclaw',
    from: 'Prague',
    city: 'Wrocław',
    h2: 'Prague to Wrocław Private Transfer',
    country: 'Poland',
    tier: 'yellow',
    distanceKm: 285,
    distance: '~285 km',
    duration: '~3 hours',
    road: null,
    prices: { eClass: 470, sClass: 700, vClass: 540 },
    priceFrom: 'From €470',
    description: 'Poland\'s Venice of the North. Three hours through Lower Silesia — university city, medieval market square, MICE hub.',
    notes: [],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to Wrocław Private Transfer — From €470',
  },
  {
    slug: 'prague-vienna',
    from: 'Prague',
    city: 'Vienna',
    h2: 'Prague to Vienna Private Chauffeur',
    country: 'Austria',
    tier: 'green',
    distanceKm: 295,
    distance: '~295 km',
    duration: '~3.5 hours',
    road: 'Motorway D1/A22',
    prices: { eClass: 485, sClass: 725, vClass: 560 },
    priceFrom: 'From €485',
    description: 'The classic Central European route. 295 km through the Bohemian countryside, arriving in Vienna\'s Innere Stadt. Business class, without the airport.',
    notes: ['Flight tracking from Vienna Airport on return', 'Stops available on request (Bratislava, Brno)'],
    image: '/vienna.png',
    wordTarget: 1500,
    metadataTitle: 'Prague to Vienna Private Chauffeur Transfer — From €485',
  },
  {
    slug: 'prague-salzburg',
    from: 'Prague',
    city: 'Salzburg',
    h2: 'Prague to Salzburg Chauffeur',
    country: 'Austria',
    tier: 'green',
    distanceKm: 305,
    distance: '~305 km',
    duration: '~3.5 hours',
    road: null,
    prices: { eClass: 505, sClass: 750, vClass: 580 },
    priceFrom: 'From €505',
    description: 'Mozart, the Fortress, and the Alps. 305 km southwest — business, leisure, or a Festspiele weekend.',
    notes: [],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Salzburg Private Transfer — From €505',
  },
  {
    slug: 'prague-zlin',
    from: 'Prague',
    city: 'Zlín',
    h2: 'Prague to Zlín Chauffeur',
    country: 'Czech Republic',
    tier: 'yellow',
    distanceKm: 310,
    distance: '~310 km',
    duration: '~3.5 hours',
    road: null,
    prices: { eClass: 510, sClass: 760, vClass: 590 },
    priceFrom: 'From €510',
    description: 'The functionalist company town on the Dřevnice. 310 km southeast — Baťa\'s legacy, constructivist architecture, and an international film festival with a global reputation.',
    notes: ['Olomouc stop available en route'],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to Zlín Private Transfer — From €510',
  },
  {
    slug: 'prague-bratislava',
    from: 'Prague',
    city: 'Bratislava',
    h2: 'Prague to Bratislava Chauffeur',
    country: 'Slovakia',
    tier: 'green',
    distanceKm: 330,
    distance: '~330 km',
    duration: '~3.5 hours',
    road: null,
    prices: { eClass: 545, sClass: 810, vClass: 625 },
    priceFrom: 'From €545',
    description: 'Slovakia\'s capital on the Danube. EU institutions, corporate travel, weekend breaks — 330 km, 3.5 hours.',
    notes: [],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Bratislava Private Transfer — From €545',
  },
  {
    slug: 'prague-berlin',
    from: 'Prague',
    city: 'Berlin',
    h2: 'Prague to Berlin Private Transfer',
    country: 'Germany',
    tier: 'green',
    distanceKm: 350,
    distance: '~350 km',
    duration: '~4 hours',
    road: 'Motorway D8/A17',
    prices: { eClass: 580, sClass: 860, vClass: 665 },
    priceFrom: 'From €580',
    description: 'Four hours north through Dresden. Board meetings, trade shows, weekend escapes. One vehicle, one price, no connections.',
    notes: ['Dresden stopover available', 'Return journeys bookable online'],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Berlin Private Transfer | Door-to-Door in 4 Hours | Prestigo',
  },
  {
    slug: 'prague-nuremberg',
    from: 'Prague',
    city: 'Nuremberg',
    h2: 'Prague to Nuremberg Chauffeur',
    country: 'Germany',
    tier: 'green',
    distanceKm: 360,
    distance: '~360 km',
    duration: '~3.5 hours',
    road: 'Motorway D5/A93',
    prices: { eClass: 595, sClass: 880, vClass: 685 },
    priceFrom: 'From €595',
    description: 'Medieval Altstadt, the Christmas market, BMW day trips. 360 km southwest through Pilsen and Bavaria.',
    notes: [],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Nuremberg Private Transfer — From €595',
  },
  {
    slug: 'prague-ostrava',
    from: 'Prague',
    city: 'Ostrava',
    h2: 'Prague to Ostrava Chauffeur',
    country: 'Czech Republic',
    tier: 'yellow',
    distanceKm: 370,
    distance: '~370 km',
    duration: '~4 hours',
    road: 'Motorway D1',
    prices: { eClass: 610, sClass: 905, vClass: 705 },
    priceFrom: 'From €610',
    description: 'Czech industrial heritage transformed. 370 km northeast — Dolní Vítkovice arts precinct, Colours of Ostrava festival, and the Slovak and Polish borders within reach.',
    notes: ['Olomouc stop available en route', 'Katowice (Poland) nearby'],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to Ostrava Private Transfer — From €610',
  },
  {
    slug: 'prague-krakow',
    from: 'Prague',
    city: 'Kraków',
    h2: 'Prague to Kraków Chauffeur',
    country: 'Poland',
    tier: 'green',
    distanceKm: 385,
    distance: '~385 km',
    duration: '~4 hours',
    road: null,
    prices: { eClass: 635, sClass: 945, vClass: 730 },
    priceFrom: 'From €635',
    description: 'The royal capital and cultural heart of Poland. Four hours east on the expressway — Wawel, Kazimierz, and Auschwitz visits.',
    notes: [],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Kraków Private Transfer — From €635',
  },
  {
    slug: 'prague-munich',
    from: 'Prague',
    city: 'Munich',
    h2: 'Prague to Munich Chauffeur Service',
    country: 'Germany',
    tier: 'green',
    distanceKm: 385,
    distance: '~385 km',
    duration: '~4 hours',
    road: 'Motorway D5/A93',
    prices: { eClass: 635, sClass: 945, vClass: 730 },
    priceFrom: 'From €635',
    description: 'West through Pilsen and Bavaria. Oktoberfest, business parks, the Munich airport — PRESTIGO covers every reason to travel.',
    notes: ['Munich Airport (MUC) pickups included'],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Munich Private Transfer — From €635',
  },
  {
    slug: 'prague-graz',
    from: 'Prague',
    city: 'Graz',
    h2: 'Prague to Graz Private Transfer',
    country: 'Austria',
    tier: 'yellow',
    distanceKm: 450,
    distance: '~450 km',
    duration: '~4.5 hours',
    road: null,
    prices: { eClass: 745, sClass: 1105, vClass: 855 },
    priceFrom: 'From €745',
    description: 'Styria\'s capital and a UNESCO city of design. 450 km south of Prague — four and a half hours, door to door.',
    notes: [],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to Graz Private Transfer — From €745',
  },
  {
    slug: 'prague-budapest',
    from: 'Prague',
    city: 'Budapest',
    h2: 'Prague to Budapest Private Driver',
    country: 'Hungary',
    tier: 'green',
    distanceKm: 535,
    distance: '~535 km',
    duration: '~5.5 hours',
    road: null,
    prices: { eClass: 885, sClass: 1310, vClass: 1015 },
    priceFrom: 'From €885',
    description: 'Brno, Vienna, and the Danube bend — five and a half hours that feel curated. Grand baths, ruin bars, parliament views.',
    notes: ['Vienna and Bratislava stops available'],
    image: null,
    wordTarget: 1500,
    metadataTitle: 'Prague to Budapest Private Transfer — From €885',
  },
  {
    slug: 'prague-warsaw',
    from: 'Prague',
    city: 'Warsaw',
    h2: 'Prague to Warsaw Private Chauffeur',
    country: 'Poland',
    tier: 'yellow',
    distanceKm: 660,
    distance: '~660 km',
    duration: '~7 hours',
    road: null,
    prices: { eClass: 1090, sClass: 1615, vClass: 1255 },
    priceFrom: 'From €1,090',
    description: 'Poland\'s capital. Seven hours northeast — government visits, board meetings, tech sector. No connections, no delays.',
    notes: ['Wrocław or Kraków stopover available'],
    image: null,
    wordTarget: 900,
    metadataTitle: 'Prague to Warsaw Private Transfer — From €1,090',
  },
]

export const ROUTES_BY_SLUG: Record<string, Route> = Object.fromEntries(
  ROUTES.map((r) => [r.slug, r])
)

export const GREEN_ROUTES = ROUTES.filter((r) => r.tier === 'green')
export const YELLOW_ROUTES = ROUTES.filter((r) => r.tier === 'yellow')

// Countries in ascending distance order (natural for hub grouping)
export const ROUTE_COUNTRIES = Array.from(new Set(ROUTES.map((r) => r.country)))
