#!/usr/bin/env python3
"""hreflang reciprocity validator (D-14, VER-01).

Parses /sitemap.xml (generated by app/sitemap.ts from lib/seo.ts's
getAlternates(), the single source of both surfaces — see key_links).
Every <url> entry in this sitemap is keyed by its EN canonical URL and
carries the FULL alternate cluster (all 7 locale hreflang tags + x-default)
inline — there is no separate sitemap <url> entry per non-EN locale. So the
meaningful reciprocity check for this structure is:

  1. Structural completeness: every cluster carries exactly the expected
     BCP-47 hreflang set (en, ru, es, fr, ar, hi, zh-Hans) plus x-default,
     and x-default equals the cluster's own 'en' href (D-14: x-default must
     be the EN root form).
  2. Reachability: every distinct alternate href across every cluster
     returns 200 (sequential requests, 20s timeout, 1 retry).
  3. Cross-surface reciprocity: for a sample of clusters, the EN page's own
     rendered <link rel="alternate" hreflang> tags (page-level surface) are
     fetched and diffed against the sitemap cluster (sitemap surface) — a
     mismatch here is the concrete "non-reciprocal alternate pair" failure,
     since both surfaces are supposed to be generated by the same
     getAlternates() call and can never legitimately diverge.

Usage: python3 scripts/qa/hreflang_reciprocity.py [base_url]
Writes scripts/qa/out/hreflang_reciprocity.json.
Exit codes: 0 = clean, 1 = findings present, 2 = infrastructure error.
"""
import argparse
import json
import os
import re
import ssl
import sys
import xml.etree.ElementTree as ET
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

try:
    import certifi
    SSL_CONTEXT = ssl.create_default_context(cafile=certifi.where())
except ImportError:
    SSL_CONTEXT = None  # fall back to the interpreter's default verify paths

NS = {
    'ns': 'http://www.sitemaps.org/schemas/sitemap/0.9',
    'xhtml': 'http://www.w3.org/1999/xhtml',
}

EXPECTED_HREFLANGS = ['en', 'ru', 'es', 'fr', 'ar', 'hi', 'zh-Hans']

# i18n/locales.ts BCP47_TAG — zh maps to zh-Hans, every other locale to itself.
BCP47_TAG = {'en': 'en', 'ru': 'ru', 'es': 'es', 'fr': 'fr', 'ar': 'ar', 'hi': 'hi', 'zh': 'zh-Hans'}

# Fixed order per D-14 spot-check requirement.
SAMPLE_PATHS = [
    '', '/fleet', '/book', '/routes', '/routes/prague-vienna',
    '/services/airport-transfer', '/faq', '/about', '/contact', '/blog',
]

OUT_DIR = os.path.join('scripts', 'qa', 'out')
OUT_PATH = os.path.join(OUT_DIR, 'hreflang_reciprocity.json')

LINK_TAG_RE = re.compile(
    r'<link\s+rel="alternate"\s+hreflang="([^"]+)"\s+href="([^"]+)"',
    re.IGNORECASE,
)


def fetch(url: str, timeout: int = 20, retries: int = 1):
    last_err = None
    for _ in range(retries + 1):
        try:
            req = Request(url, headers={'User-Agent': 'PrestigoQA/1.0'})
            with urlopen(req, timeout=timeout, context=SSL_CONTEXT) as resp:
                return resp.status, resp.read()
        except HTTPError as e:
            return e.code, b''
        except URLError as e:
            last_err = e
    raise last_err


def main() -> int:
    parser = argparse.ArgumentParser(description='hreflang_reciprocity — VER-01/D-14 sitemap<->page-level check')
    parser.add_argument('base_url', nargs='?', default='https://rideprestigo.com')
    parser.add_argument('--locales', default='en,ru,es,fr,ar,hi,zh')
    args = parser.parse_args()
    base = args.base_url.rstrip('/')
    requested_locales = [l.strip() for l in args.locales.split(',') if l.strip()]
    requested_tags = {BCP47_TAG.get(l, l) for l in requested_locales}
    expected_hreflangs = [h for h in EXPECTED_HREFLANGS if h in requested_tags] or EXPECTED_HREFLANGS

    os.makedirs(OUT_DIR, exist_ok=True)

    clusters: dict = {}
    try:
        status, body = fetch(f'{base}/sitemap.xml')
        if status != 200:
            print(f'INFRA ERROR: /sitemap.xml returned {status}', file=sys.stderr)
            return 2
        root = ET.fromstring(body)
        for url_el in root.findall('ns:url', NS):
            loc_el = url_el.find('ns:loc', NS)
            if loc_el is None or not loc_el.text:
                continue
            loc = loc_el.text
            alts = {
                link.get('hreflang'): link.get('href')
                for link in url_el.findall('xhtml:link', NS)
            }
            clusters[loc] = alts
    except Exception as e:
        print(f'INFRA ERROR: {e}', file=sys.stderr)
        return 2

    structural_findings = []
    for loc, alts in clusters.items():
        missing = [h for h in expected_hreflangs if h not in alts]
        if missing:
            structural_findings.append(f'{loc}: missing hreflang entries {missing}')
        if 'x-default' not in alts:
            structural_findings.append(f'{loc}: missing x-default')
        elif alts.get('x-default') != alts.get('en'):
            structural_findings.append(
                f"{loc}: x-default={alts.get('x-default')!r} is not the EN root form (expected {alts.get('en')!r})"
            )

    # Reachability: every distinct href across every cluster, in cluster/
    # hreflang document order (deterministic, dedup preserves first-seen order).
    reachable_tags = requested_tags | {'x-default'}
    seen_urls: list = []
    seen_set: set = set()
    for loc, alts in clusters.items():
        for hreflang in list(alts.keys()):
            if hreflang not in reachable_tags:
                continue
            href = alts[hreflang]
            if href and href not in seen_set:
                seen_set.add(href)
                seen_urls.append(href)

    reachability_findings = []
    checked = 0
    try:
        for href in seen_urls:
            checked += 1
            try:
                status, _ = fetch(href)
            except Exception as e:
                reachability_findings.append(f'{href}: request error {str(e)[:120]}')
                continue
            if status != 200:
                reachability_findings.append(f'{href}: status={status} (expected 200)')
    except Exception as e:
        print(f'INFRA ERROR during reachability pass: {e}', file=sys.stderr)
        return 2

    # Cross-surface reciprocity: sampled clusters, EN page's own rendered
    # hreflang link tags vs the sitemap cluster for that same EN URL.
    reciprocity_findings = []
    sampled = []
    for path in SAMPLE_PATHS:
        en_url = base if path == '' else base + path
        cluster = clusters.get(en_url)
        if cluster is None:
            reciprocity_findings.append(f'{en_url}: not found in sitemap (cannot spot-check)')
            continue
        try:
            status, body = fetch(en_url)
        except Exception as e:
            reciprocity_findings.append(f'{en_url}: page fetch error {str(e)[:120]}')
            continue
        if status != 200:
            reciprocity_findings.append(f'{en_url}: page returned status={status}')
            continue
        html = body.decode('utf-8', errors='replace')
        page_tags = {m.group(1): m.group(2) for m in LINK_TAG_RE.finditer(html)}
        sampled.append({'url': en_url, 'sitemapCluster': cluster, 'pageTags': page_tags})
        if page_tags != cluster:
            only_sitemap = {k: v for k, v in cluster.items() if page_tags.get(k) != v}
            only_page = {k: v for k, v in page_tags.items() if cluster.get(k) != v}
            reciprocity_findings.append(
                f'{en_url}: NOT reciprocal — sitemap surface {only_sitemap} != page surface {only_page}'
            )

    result = {
        'baseUrl': base,
        'clustersChecked': len(clusters),
        'alternateUrlsChecked': checked,
        'structuralFindings': structural_findings,
        'reachabilityFindings': reachability_findings,
        'sampledClusters': sampled,
        'reciprocityFindings': reciprocity_findings,
    }

    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        json.dump(result, f, ensure_ascii=False, indent=1)

    total_errors = len(structural_findings) + len(reachability_findings) + len(reciprocity_findings)
    print(f'{len(clusters)} sitemap URLs checked, {checked} alternate URLs verified, {total_errors} reciprocity errors')
    for e in structural_findings + reachability_findings + reciprocity_findings:
        print('  ', e)

    return 1 if total_errors else 0


if __name__ == '__main__':
    sys.exit(main())
